name: Linter and Tests


on:
  push:
  pull_request:
    branches: main

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked

      - name: Run tests
        run: uv run coverage --branch -m pytest

      - name: Check coverage
        run: uv run coverage report --include "src/*" --skip-covered --skip-empty --show-missing --fail-under=70
